
# Global parameters

global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  storageClass: ""
  security:
    allowInsecureImages: false
  compatibility:
    openshift:
      adaptSecurityContext: auto
# Common parameters

kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
commonAnnotations: {}
commonLabels: {}
extraDeploy: []
clusterDomain: cluster.local
usePasswordFiles: true
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
# Kibana parameters

image:
  registry: ghcr.io
  repository: nix-containers/kibana-nixchart
  tag: 9.1.2-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
replicaCount: 1
updateStrategy:
  type: RollingUpdate
revisionHistoryLimit: 10
schedulerName: ""
priorityClassName: ""
terminationGracePeriodSeconds: ""
topologySpreadConstraints: []
automountServiceAccountToken: false
hostAliases: []
plugins: []
savedObjects:
  urls: []
  configmap: ""
  overwrite: false
extraConfiguration: {}
configurationCM: ""
command: []
args: []
lifecycleHooks: {}
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
extraVolumes: []
extraVolumeMounts: []
volumePermissions:
  enabled: false
  image:
    registry: ghcr.io
    repository: nix-containers/os-shell-nixchart
    tag: 12-debian-12-r50
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  resourcesPreset: "nano"
  resources: {}
persistence:
  enabled: true
  storageClass: ""
  existingClaim: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}
  subPath: ""
  selector: {}
  dataSource: {}
startupProbe:
  enabled: false
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
customStartupProbe: {}
customLivenessProbe: {}
customReadinessProbe: {}
forceInitScripts: false
initScriptsCM: ""
initScriptsSecret: ""
service:
  ports:
    http: 5601
  type: ClusterIP
  nodePorts:
    http: ""
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  annotations: {}
  labels: {}
  extraPorts: []
  sessionAffinity: None
  sessionAffinityConfig: {}
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
ingress:
  enabled: false

  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: kibana.local
  path: /
  annotations: {}
  tls: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  ingressClassName: ""
  extraRules: []
serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: false
  annotations: {}
containerPorts:
  http: 5601
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001
containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
resourcesPreset: "small"
resources: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
podAnnotations: {}
podLabels: {}
sidecars: []
initContainers: []
pdb:
  create: true
  minAvailable: ""
  maxUnavailable: ""
configuration:
  server:
    basePath: ""
    host: "0.0.0.0"
    publicBaseUrl: ""
    rewriteBasePath: false
metrics:
  enabled: false
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
      prometheus.io/path: "_prometheus/metrics"
  serviceMonitor:
    enabled: false
    namespace: ""
    jobLabel: ""
    interval: ""
    scrapeTimeout: ""
    relabelings: []
    metricRelabelings: []
    # selector:
    #   prometheus: my-prometheus
    selector: {}
    labels: {}
    honorLabels: false
# Kibana server TLS configuration
tls:
  enabled: false
  autoGenerated: false
  existingSecret: ""
  usePemCerts: false
  keyPassword: ""
  keystorePassword: ""
  passwordsSecret: ""
# Elasticsearch parameters
elasticsearch:
  hosts: []
  port: ""
  security:
    auth:
      enabled: false
      kibanaPassword: ""
      existingSecret: ""
      createSystemUser: false
      elasticsearchPasswordSecret: ""
    tls:
      enabled: false
      verificationMode: "full"
      existingSecret: ""
      usePemCerts: false
      truststorePassword: ""
      passwordsSecret: ""
