
# Global parameters

global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  security:
    allowInsecureImages: false
  compatibility:
    openshift:
      adaptSecurityContext: auto
# Common parameters

kubeVersion: ""
apiVersions: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
commonLabels: {}
commonAnnotations: {}
clusterDomain: cluster.local
extraDeploy: []
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
# MLflow common Parameters

image:
  registry: ghcr.io
  repository: nix-containers/mlflow-nixchart
  tag: 3.3.2-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
gitImage:
  registry: ghcr.io
  repository: nix-containers/git-nixchart
  tag: 2.51.0-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
# MLflow Tracking parameters
tracking:
  enabled: true
  replicaCount: 1
  host: "0.0.0.0"
  containerPorts:
    http: 5000
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  resourcesPreset: "medium"
  resources: {}
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  auth:
    enabled: true
    username: user
    password: ""
    flaskServerSecretKey: ""
    existingSecret: ""
    existingSecretUserKey: ""
    existingSecretPasswordKey: ""
    existingSecretFlaskServerSecretKey: ""
    extraOverrides: {}
    overridesConfigMap: ""
  tls:
    enabled: false
    autoGenerated: false
    certificatesSecret: ""
    certFilename: ""
    certKeyFilename: ""
    certCAFilename: ""
  command: []
  args: []
  extraArgs: []
  runUpgradeDB: false
  automountServiceAccountToken: false
  hostAliases: []
  podLabels: {}
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""
  autoscaling:
    hpa:
      enabled: false
      minReplicas: ""
      maxReplicas: ""
      targetCPU: ""
      targetMemory: ""
    vpa:
      enabled: false
      annotations: {}
      controlledResources: []
      maxAllowed: {}
      minAllowed: {}
      updatePolicy:
        updateMode: Auto
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  updateStrategy:
    type: RollingUpdate
  priorityClassName: ""
  topologySpreadConstraints: []
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  lifecycleHooks: {}
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: []
  enableDefaultInitContainers: true
  initContainers: []
  # MLflow Tracking Traffic Exposure Parameters

  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
    nodePorts:
      http: ""
      https: ""
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    labels: {}
    externalTrafficPolicy: Cluster
    annotations: {}
    extraPorts: []
    sessionAffinity: None
    sessionAffinityConfig: {}
  ingress:
    enabled: false
    pathType: ImplementationSpecific
    hostname: mlflow.local
    ingressClassName: ""
    path: /
    annotations: {}
    tls: false
    selfSigned: false
    extraHosts: []
    extraPaths: []
    extraTls: []
    secrets: []
    extraRules: []
  # tracking.httproute Gateway API HTTPRoute configuration
  httproute:
      enabled: false
      annotations: {}
      labels: {}
      parentRefs: []
      hostnames:
        - mlflow.local
      matches:
        - path:
            type: PathPrefix
            value: /
      filters: []
      extraRules: []
  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true
    extraIngress: []
    extraEgress: []
    ingressNSMatchLabels: {}
    ingressNSPodMatchLabels: {}
  # MLflow Tracking Persistence Parameters

  persistence:
    enabled: true
    mountPath: /nix-containers/mlflow
    subPath: ""
    storageClass: ""
    labels: {}
    annotations: {}
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    existingClaim: ""
    selector: {}
    dataSource: {}

  tmpVolume:
    ephemeral:
      enabled: false
      volumeClaimTemplate: {}

  # MLflow Tracking Other Parameters
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    automountServiceAccountToken: false

  # MLflow Tracking Metrics Parameters
  metrics:
    enabled: false
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.tracking.service.ports.http }}"
    serviceMonitor:
      enabled: false
      namespace: ""
      annotations: {}
      labels: {}
      jobLabel: ""
      honorLabels: false
      interval: ""
      scrapeTimeout: ""
      metricRelabelings: []
      relabelings: []
      selector: {}
# MLflow Run Parameters
run:
  enabled: true
  useJob: false
  backoffLimit: 10
  restartPolicy: OnFailure
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  annotations: {}
  command: []
  args: []
  terminationGracePeriodSeconds: ""
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  resourcesPreset: "small"
  resources: {}
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  lifecycleHooks: {}
  ##https://github.com/microsoft/MlflowExamples
  runtimeClassName: ""
  automountServiceAccountToken: false
  hostAliases: []
  labels: {}
  podLabels: {}
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  priorityClassName: ""
  schedulerName: ""
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: {}
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: []
  enableDefaultInitContainers: true
  initContainers: []
  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true
    extraIngress: []
    extraEgress: []
    ingressNSMatchLabels: {}
    ingressNSPodMatchLabels: {}
  source:
    type: "configmap"
    launchCommand: ""
    configMap: {}
    existingConfigMap: ""
    git:
      repository: ""
      revision: ""
      extraVolumeMounts: []
  serviceAccount:
    create: true
    name: ""
    automountServiceAccountToken: false
    annotations: {}
  # Mlflow Run persistence paramaters
  persistence:
    enabled: false
    storageClass: ""
    existingClaim: ""
    mountPath: /nix-containers/mlflow/data
    subPath: ""
    accessModes:
      - ReadWriteOnce
    dataSource: {}
    selector: {}
    size: 8Gi
    labels: {}
    annotations: {}
# Init Container Parameters

volumePermissions:
  enabled: false
  image:
    registry: ghcr.io
    repository: nix-containers/os-shell-nixchart
    tag: 12-debian-12-r51
    pullPolicy: IfNotPresent
    pullSecrets: []
  resourcesPreset: "nano"
  resources: {}
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 0
waitContainer:
  image:
    registry: ghcr.io
    repository: nix-containers/os-shell-nixchart
    tag: 12-debian-12-r51
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
# PostgreSQL chart configuration
postgresql:
  enabled: true
  auth:
    username: bn_mlflow
    password: ""
    database: nix-containers_mlflow
    existingSecret: ""
  architecture: standalone
  primary:
    service:
      ports:
        postgresql: 5432
    initdb:
      scripts:
        # For authentication, Mlflow requires a different database in order to work
        create_auth_db.sh: |
          #!/bin/bash
          PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD psql -U postgres <<< "CREATE DATABASE {{ include "mlflow.v0.database-auth.name" . }}"
          PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD psql -U postgres <<< "GRANT ALL PRIVILEGES ON DATABASE {{ include "mlflow.v0.database-auth.name" . }} to {{ .Values.auth.username }}"
          PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD psql -U postgres <<< "ALTER DATABASE {{ include "mlflow.v0.database-auth.name" . }} OWNER TO {{ .Values.auth.username }}"
# External PostgreSQL configuration
externalDatabase:
  dialectDriver: "postgresql"
  host: ""
  port: 5432
  user: postgres
  database: mlflow
  authDatabase: mlflow_auth
  password: ""
  existingSecret: ""
  existingSecretPasswordKey: "db-password"
# MinIO&reg; chart parameters
minio:
  enabled: true
  auth:
    rootUser: admin
    rootPassword: ""
    existingSecret: ""
  defaultBuckets: "mlflow"
  provisioning:
    enabled: true
    # We need to allow downloads in order for the UI to work
    extraCommands: ["mc anonymous set download provisioning/mlflow"]
  tls:
    enabled: false
  service:
    type: ClusterIP
    loadBalancerIP: ""
    ports:
      api: 80
  console:
    enabled: false

# External S3 parameters
externalS3:
  host: ""
  port: 443
  useCredentialsInSecret: true
  accessKeyID: ""
  accessKeySecret: ""
  existingSecret: ""
  existingSecretAccessKeyIDKey: "root-user"
  existingSecretKeySecretKey: "root-password"
  protocol: "https"
  bucket: "mlflow"
  serveArtifacts: true

# External Google Cloud Storage parameters
externalGCS:
  bucket: ""
  googleCloudProject: ""
  useCredentialsInSecret: false
  existingSecret: ""
  existingSecretKey: ""
  serveArtifacts: true

# External Azure Blob Storage parameters
externalAzureBlob:
  storageAccount: ""
  accessKey: ""
  connectionString: ""
  containerName: "mlflow"
  clientId: ""
  tenantId: ""
  clientSecret: ""
  useCredentialsInSecret: false
  existingSecret: ""
  existingAccessKeyKey: ""
  existingConnectionStringKey: ""
  clientSecretKey: ""
  serveArtifacts: true
