
# Global parameters

global:
  imageRegistry: ""
  imagePullSecrets: []
  security:
    allowInsecureImages: false
  compatibility:
    openshift:
      adaptSecurityContext: auto
# Common parameters

nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
clusterDomain: cluster.local
commonLabels: {}
commonAnnotations: {}
extraDeploy: []
kubeVersion: ""

# external-dns parameters

image:
  registry: ghcr.io
  repository: nix-containers/external-dns-nixchart
  tag: v0.21.0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
revisionHistoryLimit: 10
automountServiceAccountToken: true
hostAliases: []
updateStrategy: {}
command: []
args: []
sources:
  # - crd
  - service
  - ingress
  # - contour-httpproxy
provider: aws
initContainers: []
dnsPolicy: ""
dnsConfig: {}
sidecars: []
namespace: ""
watchReleaseNamespace: false
fqdnTemplates: []
containerPorts:
  http: 7979
combineFQDNAnnotation: false
ignoreHostnameAnnotation: false
publishInternalServices: false
publishHostIP: false
serviceTypeFilter: []
validation:
  enabled: true
akamai:
  host: ""
  accessToken: ""
  clientToken: ""
  clientSecret: ""
  secretName: ""
alibabacloud:
  accessKeyId: ""
  accessKeySecret: ""
  regionId: ""
  vpcId: ""
  secretName: ""
  zoneType: ""
aws:
  credentials:
    secretKey: ""
    accessKey: ""
    mountPath: "/.aws"
    secretName: ""
    accessKeyIDSecretRef:
      name: ""
      key: ""
    secretAccessKeySecretRef:
      name: ""
      key: ""
  region: "us-east-1"
  zoneType: ""
  assumeRoleArn: ""
  roleArn: ""
  apiRetries: 3
  batchChangeSize: 1000
  zonesCacheDuration: 0
  zoneTags: []
  preferCNAME: ""
  evaluateTargetHealth: ""
  dynamodbTable: ""
  dynamodbRegion: ""
  zoneMatchParent: false
azure:
  secretName: ""
  cloud: ""
  resourceGroup: ""
  tenantId: ""
  subscriptionId: ""
  aadClientId: ""
  aadClientSecret: ""
  useWorkloadIdentityExtension: false
  useManagedIdentityExtension: false
  userAssignedIdentityID: ""
civo:
  apiToken: ""
  secretName: ""
cloudflare:
  apiToken: ""
  apiKey: ""
  secretName: ""
  email: ""
  proxied: true
  dnsRecordsPerPage: 100
  regionalServices: false
  regionKey: ""
coredns:
  etcdEndpoints: "http://etcd-extdns:2379"
  etcdTLS:
    enabled: false
    autoGenerated: false
    secretName: "etcd-client-certs"
    mountPath: "/etc/coredns/tls/etcd"
    caFilename: "ca.crt"
    certFilename: "cert.pem"
    keyFilename: "key.pem"
exoscale:
  apiKey: ""
  apiToken: ""
  secretName: ""
digitalocean:
  apiToken: ""
  secretName: ""
google:
  project: ""
  batchChangeSize: 1000
  serviceAccountSecret: ""
  serviceAccountSecretKey: "credentials.json"
  serviceAccountKey: ""
  zoneVisibility: ""
linode:
  apiToken: ""
  secretName: ""
ns1:
  minTTL: 10
  apiKey: ""
  secretName: ""
pihole:
  server: ""
  tlsSkipVerify: ""
  password: ""
  secretName: ""
traefik:
  disableNew: false
  disableLegacy: false
oci:
  region: ""
  tenancyOCID: ""
  userOCID: ""
  compartmentOCID: ""
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----
  privateKeyFingerprint: ""
  privateKeyPassphrase: ""
  secretName: ""
  useInstancePrincipal: false
  useWorkloadIdentity: false
ovh:
  consumerKey: ""
  applicationKey: ""
  applicationSecret: ""
  secretName: ""
scaleway:
  scwAccessKey: ""
  scwSecretKey: ""
  secretName: ""
rfc2136:
  host: ""
  port: 53
  zone: ""
  zones: []
  tsigSecret: ""
  secretName: ""
  tsigSecretAlg: hmac-sha256
  tsigKeyname: rfc2136_tsig_secret
  tsigAxfr: true
  minTTL: "0s"
  rfc3645Enabled: false
  kerberosConfig: ""
  kerberosUsername: ""
  kerberosPassword: ""
  kerberosRealm: ""
pdns:
  apiUrl: ""
  apiPort: "8081"
  apiKey: ""
  secretName: ""
transip:
  account: ""
  apiKey: ""
domainFilters: []
excludeDomains: []
regexDomainFilter: ""
regexDomainExclusion: ""
zoneNameFilters: []
zoneIdFilters: []
annotationFilter: ""
labelFilter: ""
ingressClassFilters: []
managedRecordTypesFilters: []
dryRun: false
triggerLoopOnEvent: false
interval: "1m"
logLevel: info
logFormat: text
policy: upsert-only
registry: "txt"
txtPrefix: ""
txtSuffix: ""
txtNewFormatOnly: false
txtOwnerId: ""
forceTxtOwnerId: false
txtEncrypt:
  enabled: false
  aesKey: ""
  secretName: ""
extraArgs: {}
##extraArgs:
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
lifecycleHooks: {}
schedulerName: ""
topologySpreadConstraints: []
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
podAnnotations: {}
podLabels: {}
priorityClassName: ""
secretAnnotations: {}
crd:
  create: false
  apiversion: ""
  kind: ""
service:
  enabled: true
  type: ClusterIP
  ports:
    http: 7979
  nodePorts:
    http: ""
  clusterIP: ""
  externalIPs: []
  externalName: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  extraPorts: []
  annotations: {}
  labels: {}
  sessionAffinity: None
  sessionAffinityConfig: {}
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
  kubeAPIServerPorts: [443, 6443, 8443]
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false
  labels: {}
rbac:
  create: true
  clusterRole: true
  apiVersion: v1
containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001
resourcesPreset: "nano"
resources: {}
livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
startupProbe:
  enabled: false
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
customLivenessProbe: {}
customReadinessProbe: {}
customStartupProbe: {}
extraVolumes: []
extraVolumeMounts: []
pdb:
  create: true
  minAvailable: ""
  maxUnavailable: ""
metrics:
  enabled: false
  podAnnotations: {}
  serviceMonitor:
    enabled: false
    namespace: ""
    interval: ""
    scrapeTimeout: ""
    selector: {}
    metricRelabelings: []
    relabelings: []
    honorLabels: false
    labels: {}
    targetLabels: []
    podTargetLabels: []
    annotations: {}
    jobLabel: ""
  googlePodMonitor:
    enabled: false
    namespace: ""
    interval: "60s"
    endpoint: /metrics
