
# Global parameters

global:
  imageRegistry: ""
  imagePullSecrets: []
  security:
    allowInsecureImages: false
  compatibility:
    openshift:
      adaptSecurityContext: auto
# Common parameters

kubeVersion: ""
apiVersions: []
nameOverride: ""
fullnameOverride: ""
commonAnnotations: {}
commonLabels: {}
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
extraDeploy: []
# Kubernetes Event Exporter parameters

replicaCount: 1
revisionHistoryLimit: 10
containerPorts:
  http: 2112
extraContainerPorts: []
image:
  registry: ghcr.io
  repository: nix-containers/kubernetes-event-exporter-nixchart
  tag: 1.7.0-debian-12-r46
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
automountServiceAccountToken: true
hostAliases: []
config:
  logLevel: debug
  logFormat: pretty
  clusterName: ""
  receivers:
    - name: "dump"
      file:
        path: "/dev/stdout"
        layout: null
  route:
    routes:
      - match:
          - receiver: "dump"
rbac:
  create: true
  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["get", "watch", "list"]
serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: false
  annotations: {}
podAnnotations: {}
podLabels: {}
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001
pdb:
  create: true
  minAvailable: ""
  maxUnavailable: ""
containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
command: []
args: []
lifecycleHooks: {}
resourcesPreset: "nano"
resources: {}
networkPolicy:
  enabled: true
  kubeAPIServerPorts: [443, 6443, 8443]
  allowExternal: true
  allowExternalEgress: true
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 5
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 1
  successThreshold: 1
startupProbe:
  enabled: false
  initialDelaySeconds: 40
  periodSeconds: 10
  timeoutSeconds: 15
  failureThreshold: 15
  successThreshold: 1
customStartupProbe: {}
customLivenessProbe: {}
customReadinessProbe: {}
nodeSelector: {}
priorityClassName: ""
schedulerName: ""
topologySpreadConstraints: []
tolerations: []
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
updateStrategy:
  type: RollingUpdate
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
extraVolumeMounts: []
extraVolumes: []
initContainers: []
sidecars: []
metrics:
  enabled: false
  service:
    ports:
      http: 2112
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.ports.http }}"
  serviceMonitor:
    enabled: false
    port: http
    endpoints:
      - path: /metrics
    path: ""
    namespace: ""
    interval: 30s
    scrapeTimeout: ""
    labels: {}
    selector: {}
    relabelings: []
    metricRelabelings: []
    honorLabels: false
    jobLabel: ""
  prometheusRule:
    enabled: false
    namespace: ""
    labels: {}
    groups: []
# Autoscaling
autoscaling:
  vpa:
    enabled: false
    annotations: {}
    recommenders: []
    controlledResources: []
    maxAllowed: {}
    minAllowed: {}
    # VPA update policy
    updatePolicy:
      minReplicas: 1
      updateMode: Auto
