
# Global parameters

global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  storageClass: ""
  security:
    allowInsecureImages: false
  namespaceOverride: ""
  compatibility:
    openshift:
      adaptSecurityContext: auto
# Common parameters

nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
kubeVersion: ""
clusterDomain: cluster.local
extraDeploy: []
commonLabels: {}
commonAnnotations: {}
topologyKey: ""
serviceBindings:
  enabled: false
enableServiceLinks: true
usePasswordFiles: true
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
# MongoDB(&reg;) parameters

image:
  registry: ghcr.io
  repository: nix-containers/mongodb-nixchart
  tag: 8.0.13-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
schedulerName: ""
architecture: standalone
useStatefulSet: false
auth:
  enabled: true
  rootUser: root
  rootPassword: ""
  usernames: []
  passwords: []
  databases: []
  username: ""
  password: ""
  database: ""
  replicaSetKey: ""
  existingSecret: ""
tls:
  enabled: false
  mTLS:
    enabled: true
  autoGenerated: true
  existingSecret: ""
  caCert: ""
  caKey: ""
  pemChainIncluded: false
  standalone:
    existingSecret: ""
  replicaset:
    existingSecrets: []
  hidden:
    existingSecrets: []
  arbiter:
    existingSecret: ""
  image:
    registry: ghcr.io
    repository: nix-containers/nginx-nixchart
    tag: 1.29.1-debian-12-r0
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  extraDnsNames: []
  mode: requireTLS
  resourcesPreset: "nano"
  resources: {}
  securityContext: {}
automountServiceAccountToken: false
hostAliases: []
replicaSetName: rs0
replicaSetHostnames: true
enableIPv6: false
directoryPerDB: false
systemLogVerbosity: 0
disableSystemLog: false
disableJavascript: false
enableJournal: true
configuration: ""
# replicaSetConfigurationSettings settings applied during runtime (not via configuration file)
replicaSetConfigurationSettings:
  enabled: false
  configuration: {}
existingConfigmap: ""
initdbScripts: {}
initdbScriptsConfigMap: ""
command: []
args: []
extraFlags: []
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
# MongoDB(&reg;) statefulset parameters

annotations: {}
labels: {}
replicaCount: 2
updateStrategy:
  type: RollingUpdate
podManagementPolicy: OrderedReady
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
topologySpreadConstraints: []
lifecycleHooks: {}
terminationGracePeriodSeconds: ""
podLabels: {}
podAnnotations: {}
priorityClassName: ""
runtimeClassName: ""
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  supplementalGroups: []
  fsGroup: 1001
  sysctls: []
containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
resourcesPreset: "small"
resources: {}
containerPorts:
  mongodb: 27017
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 10
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
startupProbe:
  enabled: false
  initialDelaySeconds: 5
  periodSeconds: 20
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 30
customLivenessProbe: {}
customReadinessProbe: {}
customStartupProbe: {}
initContainers: []
sidecars: []
extraVolumeMounts: []
extraVolumes: []
pdb:
  create: true
  minAvailable: ""
  maxUnavailable: ""
# Traffic exposure parameters

service:
  nameOverride: ""
  type: ClusterIP
  portName: mongodb
  ports:
    mongodb: 27017
  nodePorts:
    mongodb: ""
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  # ref: https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class
  loadBalancerClass: ""
  loadBalancerSourceRanges: []
  allocateLoadBalancerNodePorts: true
  extraPorts: []
  annotations: {}
  externalTrafficPolicy: Local
  sessionAffinity: None
  sessionAffinityConfig: {}
  headless:
    annotations: {}
  publishNotReadyAddresses: false
externalAccess:
  enabled: false
  autoDiscovery:
    enabled: false
    image:
      registry: ghcr.io
      repository: nix-containers/kubectl-nixchart
      tag: 1.33.4-debian-12-r0
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets: []
    resourcesPreset: "nano"
    resources: {}
  dnsCheck:
    image:
      registry: ghcr.io
      repository: nix-containers/os-shell-nixchart
      tag: 12-debian-12-r51
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets: []
    resourcesPreset: "nano"
    resources: {}
  externalMaster:
    enabled: false
    host: ""
    port: 27017
  service:
    type: LoadBalancer
    portName: "mongodb"
    ports:
      mongodb: 27017
    loadBalancerIPs: []
    publicNames: []
    # ref: https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class
    loadBalancerClass: ""
    loadBalancerSourceRanges: []
    allocateLoadBalancerNodePorts: true
    externalTrafficPolicy: Local
    nodePorts: []
    domain: ""
    extraPorts: []
    annotations: {}
    annotationsList: []
    sessionAffinity: None
    sessionAffinityConfig: {}
  hidden:
    enabled: false
    service:
      type: LoadBalancer
      portName: "mongodb"
      ports:
        mongodb: 27017
      loadBalancerIPs: []
      # ref: https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class
      loadBalancerClass: ""
      loadBalancerSourceRanges: []
      allocateLoadBalancerNodePorts: true
      externalTrafficPolicy: Local
      nodePorts: []
      domain: ""
      extraPorts: []
      annotations: {}
      sessionAffinity: None
      sessionAffinityConfig: {}
# Password update job
passwordUpdateJob:
  enabled: false
  backoffLimit: 10
  command: []
  args: []
  extraCommands: ""
  previousPasswords:
    rootPassword: ""
    existingSecret: ""
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumes: []
  extraVolumeMounts: []
  initContainers: []
  resourcesPreset: "micro"
  resources: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  automountServiceAccountToken: false
  hostAliases: []
  annotations: {}
  podLabels: {}
  podAnnotations: {}

# Network policy parameters

networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
  addExternalClientAccess: true
  extraIngress: []
  extraEgress: []
  #
  ingressPodMatchLabels: {}
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
persistence:
  enabled: true
  name: "datadir"
  medium: ""
  existingClaim: ""
  resourcePolicy: ""
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}
  labels: {}
  mountPath: /nix-containers/mongodb
  subPath: ""
  volumeClaimTemplates:
    selector: {}
    requests: {}
    dataSource: {}
persistentVolumeClaimRetentionPolicy:
  enabled: false
  whenScaled: Retain
  whenDeleted: Retain
# Backup parameters
backup:
  enabled: false
  cronjob:
    schedule: "@daily"
    timeZone: ""
    concurrencyPolicy: Allow
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    startingDeadlineSeconds: ""
    ttlSecondsAfterFinished: ""
    restartPolicy: OnFailure
    backoffLimit: 6
    serviceAccount:
      name: "default"
    containerSecurityContext:
      enabled: true
      seLinuxOptions: {}
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      privileged: false
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
    resourcesPreset: "none"
    resources: {}
    command: []
    labels: {}
    annotations: {}
    storage:
      existingClaim: ""
      resourcePolicy: ""
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 8Gi
      annotations: {}
      mountPath: /backup/mongodb
      subPath: ""
      volumeClaimTemplates:
        selector: {}
# RBAC parameters

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false
rbac:
  create: false
  rules: []
# Volume Permissions parameters
volumePermissions:
  enabled: false
  image:
    registry: ghcr.io
    repository: nix-containers/os-shell-nixchart
    tag: 12-debian-12-r51
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  resourcesPreset: "nano"
  resources: {}
  securityContext:
    seLinuxOptions: {}
    runAsUser: 0
# Arbiter parameters
arbiter:
  enabled: true
  automountServiceAccountToken: false
  hostAliases: []
  configuration: ""
  existingConfigmap: ""
  command: []
  args: []
  extraFlags: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  annotations: {}
  labels: {}
  topologySpreadConstraints: []
  lifecycleHooks: {}
  terminationGracePeriodSeconds: ""
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  schedulerName: ""
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  podLabels: {}
  podAnnotations: {}
  priorityClassName: ""
  runtimeClassName: ""
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    supplementalGroups: []
    fsGroup: 1001
    sysctls: []
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  resourcesPreset: "small"
  resources: {}
  containerPorts:
    mongodb: 27017
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 30
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  initContainers: []
  sidecars: []
  extraVolumeMounts: []
  extraVolumes: []
  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""
  service:
    nameOverride: ""
    ports:
      mongodb: 27017
    extraPorts: []
    annotations: {}
    headless:
      annotations: {}
# Hidden Node parameters
hidden:
  enabled: false
  automountServiceAccountToken: false
  hostAliases: []
  configuration: ""
  existingConfigmap: ""
  command: []
  args: []
  extraFlags: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  annotations: {}
  labels: {}
  topologySpreadConstraints: []
  lifecycleHooks: {}
  replicaCount: 1
  terminationGracePeriodSeconds: ""
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  schedulerName: ""
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  podLabels: {}
  podAnnotations: {}
  priorityClassName: ""
  runtimeClassName: ""
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    supplementalGroups: []
    fsGroup: 1001
    sysctls: []
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  resourcesPreset: "micro"
  resources: {}
  containerPorts:
    mongodb: 27017
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 30
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  initContainers: []
  sidecars: []
  extraVolumeMounts: []
  extraVolumes: []
  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""
  persistence:
    enabled: true
    medium: ""
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}
    mountPath: /nix-containers/mongodb
    subPath: ""
    volumeClaimTemplates:
      selector: {}
      requests: {}
      dataSource: {}
  service:
    nameOverride: ""
    portName: "mongodb"
    ports:
      mongodb: 27017
    extraPorts: []
    annotations: {}
    headless:
      annotations: {}
# Metrics parameters
metrics:
  enabled: false
  image:
    registry: ghcr.io
    repository: nix-containers/prometheus-mongodb-exporter-nixchart
    tag: 0.47.0-debian-12-r1
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  username: ""
  password: ""
  compatibleMode: true
  collector:
    all: false
    diagnosticdata: true
    replicasetstatus: true
    dbstats: false
    topmetrics: false
    indexstats: false
    collstats: false
    collstatsColls: []
    indexstatsColls: []
    collstatsLimit: 0
  extraFlags: ""
  command: []
  args: []
  resourcesPreset: "nano"
  resources: {}
  containerPort: 9216
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.ports.metrics }}"
      prometheus.io/path: "/metrics"
    type: ClusterIP
    ports:
      metrics: 9216
    extraPorts: []
  livenessProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 30
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraVolumeMounts: []
  serviceMonitor:
    enabled: false
    namespace: ""
    interval: 30s
    scrapeTimeout: ""
    relabelings: []
    metricRelabelings: []
    labels: {}
    selector: {}
    honorLabels: false
    jobLabel: ""
  prometheusRule:
    enabled: false
    additionalLabels: {}
    namespace: ""
    rules: []
