
# Global parameters

global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  storageClass: ""
  security:
    allowInsecureImages: false
  compatibility:
    openshift:
      adaptSecurityContext: auto
# Common parameters

kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
clusterDomain: cluster.local
commonAnnotations: {}
commonLabels: {}
extraDeploy: []
serviceBindings:
  enabled: false
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
# MySQL common parameters

image:
  registry: ghcr.io
  repository: nix-containers/mysql-nixchart
  tag: v11.4.12
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
architecture: standalone
auth:
  rootPassword: ""
  createDatabase: true
  database: "my_database"
  username: ""
  password: ""
  replicationUser: replicator
  replicationPassword: ""
  existingSecret: ""
  usePasswordFiles: true
  customPasswordFiles: {}
  authenticationPolicy: ""
initdbScripts: {}
initdbScriptsConfigMap: ""
startdbScripts: {}
startdbScriptsConfigMap: ""
# TLS/SSL parameters
tls:
  enabled: false
  existingSecret: ""
  certFilename: tls.crt
  certKeyFilename: tls.key
  certCAFilename: ""
  ca: ""
  cert: ""
  key: ""
  autoGenerated:
    enabled: true
    engine: helm
    certManager:
      existingIssuer: ""
      existingIssuerKind: ""
      keySize: 2048
      keyAlgorithm: RSA
      duration: 2160h
      renewBefore: 360h

# MySQL Primary parameters
primary:
  name: primary
  command: []
  args: []
  lifecycleHooks: {}
  automountServiceAccountToken: false
  hostAliases: []
  enableMySQLX: false
  configuration: |-
    [mysqld]
    authentication_policy='{{- .Values.auth.authenticationPolicy | default "* ,," }}'
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/nix-containers/mysql
    plugin_dir=/opt/nix-containers/mysql/lib/plugin
    port={{ .Values.primary.containerPorts.mysql }}
    mysqlx={{ ternary 1 0 .Values.primary.enableMySQLX }}
    mysqlx_port={{ .Values.primary.containerPorts.mysqlx }}
    socket=/opt/nix-containers/mysql/tmp/mysql.sock
    datadir=/nix-containers/mysql/data
    tmpdir=/opt/nix-containers/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/nix-containers/mysql/tmp/mysqld.pid
    log-error=/opt/nix-containers/mysql/logs/mysqld.log
    character-set-server=UTF8
    slow_query_log=0
    long_query_time=10.0
    {{- if .Values.tls.enabled }}
    ssl_cert=/opt/nix-containers/mysql/certs/{{ .Values.tls.certFilename }}
    ssl_key=/opt/nix-containers/mysql/certs/{{ .Values.tls.certKeyFilename }}
    {{- if (include "mysql.tlsCACert" .) }}
    ssl_ca={{ include "mysql.tlsCACert" . }}
    {{- end }}
    {{- end }}

    [client]
    port={{ .Values.primary.containerPorts.mysql }}
    socket=/opt/nix-containers/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/nix-containers/mysql/lib/plugin

    [manager]
    port={{ .Values.primary.containerPorts.mysql }}
    socket=/opt/nix-containers/mysql/tmp/mysql.sock
    pid-file=/opt/nix-containers/mysql/tmp/mysqld.pid
  existingConfigmap: ""
  containerPorts:
    mysql: 3306
    mysqlx: 33060
  updateStrategy:
    type: RollingUpdate
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  runtimeClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  topologySpreadConstraints: []
  podManagementPolicy: ""
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
    readOnlyRootFilesystem: true
  resourcesPreset: "small"
  resources: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 10
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraFlags: ""
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraPodSpec: {}
  extraPorts: []
  persistence:
    enabled: true
    existingClaim: ""
    subPath: ""
    storageClass: ""
    annotations: {}
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    selector: {}
  persistentVolumeClaimRetentionPolicy:
    enabled: false
    whenScaled: Retain
    whenDeleted: Retain
  extraVolumes: []
  extraVolumeMounts: []
  initContainers: []
  enableDefaultInitContainers: true
  sidecars: []
  service:
    type: ClusterIP
    ports:
      mysql: 3306
      mysqlx: 33060
    nodePorts:
      mysql: ""
      mysqlx: ""
    clusterIP: ""
    loadBalancerIP: ""
    externalIPs: []
    externalTrafficPolicy: Cluster
    loadBalancerSourceRanges: []
    extraPorts: []
    annotations: {}
    sessionAffinity: None
    sessionAffinityConfig: {}
    headless:
      annotations: {}
  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""
  podLabels: {}
# MySQL Secondary parameters
secondary:
  name: secondary
  replicaCount: 1
  automountServiceAccountToken: false
  hostAliases: []
  command: []
  args: []
  lifecycleHooks: {}
  enableMySQLX: false
  configuration: |-
    [mysqld]
    authentication_policy='{{- .Values.auth.authenticationPolicy | default "* ,," }}'
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/nix-containers/mysql
    plugin_dir=/opt/nix-containers/mysql/lib/plugin
    port={{ .Values.secondary.containerPorts.mysql }}
    mysqlx={{ ternary 1 0 .Values.secondary.enableMySQLX }}
    mysqlx_port={{ .Values.secondary.containerPorts.mysqlx }}
    socket=/opt/nix-containers/mysql/tmp/mysql.sock
    datadir=/nix-containers/mysql/data
    tmpdir=/opt/nix-containers/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/nix-containers/mysql/tmp/mysqld.pid
    log-error=/opt/nix-containers/mysql/logs/mysqld.log
    character-set-server=UTF8
    slow_query_log=0
    long_query_time=10.0
    {{- if .Values.tls.enabled }}
    ssl_cert=/opt/nix-containers/mysql/certs/{{ .Values.tls.certFilename }}
    ssl_key=/opt/nix-containers/mysql/certs/{{ .Values.tls.certKeyFilename }}
    {{- if (include "mysql.tlsCACert" .) }}
    ssl_ca={{ include "mysql.tlsCACert" . }}
    {{- end }}
    {{- end }}

    [client]
    port={{ .Values.secondary.containerPorts.mysql }}
    socket=/opt/nix-containers/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/nix-containers/mysql/lib/plugin

    [manager]
    port={{ .Values.secondary.containerPorts.mysql }}
    socket=/opt/nix-containers/mysql/tmp/mysql.sock
    pid-file=/opt/nix-containers/mysql/tmp/mysqld.pid
  existingConfigmap: ""
  containerPorts:
    mysql: 3306
    mysqlx: 33060
  updateStrategy:
    type: RollingUpdate
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  runtimeClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  topologySpreadConstraints: []
  podManagementPolicy: ""
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
    readOnlyRootFilesystem: true
  resourcesPreset: "small"
  resources: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraFlags: ""
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraPodSpec: {}
  extraPorts: []
  persistence:
    enabled: true
    existingClaim: ""
    subPath: ""
    storageClass: ""
    annotations: {}
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    selector: {}
  persistentVolumeClaimRetentionPolicy:
    enabled: false
    whenScaled: Retain
    whenDeleted: Retain
  extraVolumes: []
  extraVolumeMounts: []
  initContainers: []
  enableDefaultInitContainers: true
  sidecars: []
  service:
    type: ClusterIP
    ports:
      mysql: 3306
      mysqlx: 33060
    nodePorts:
      mysql: ""
      mysqlx: ""
    clusterIP: ""
    loadBalancerIP: ""
    externalIPs: []
    externalTrafficPolicy: Cluster
    loadBalancerSourceRanges: []
    extraPorts: []
    annotations: {}
    sessionAffinity: None
    sessionAffinityConfig: {}
    headless:
      annotations: {}
  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""
  podLabels: {}
# RBAC parameters

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false
rbac:
  create: false
  rules: []
# Network Policy

networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}

# Password update job
passwordUpdateJob:
  enabled: false
  backoffLimit: 10
  command: []
  args: []
  extraCommands: ""
  previousPasswords:
    rootPassword: ""
    password: ""
    replicationPassword: ""
    existingSecret: ""
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumes: []
  extraVolumeMounts: []
  initContainers: []
  resourcesPreset: "micro"
  resources: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  automountServiceAccountToken: false
  hostAliases: []
  annotations: {}
  podLabels: {}
  podAnnotations: {}

# Volume Permissions parameters

volumePermissions:
  enabled: false
  image:
    registry: ghcr.io
    repository: nix-containers/os-shell-nixchart
    tag: 12-debian-12-r50
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  resourcesPreset: "nano"
  resources: {}
# Metrics parameters

metrics:
  enabled: false
  image:
    registry: ghcr.io
    repository: nix-containers/prometheus-mysqld-exporter-nixchart
    tag: 0.17.2-debian-12-r16
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
    readOnlyRootFilesystem: true
  containerPorts:
    http: 9104
  service:
    type: ClusterIP
    port: 9104
    clusterIP: ""
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.port }}"
  extraArgs:
    primary: []
    secondary: []
  resourcesPreset: "nano"
  resources: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  serviceMonitor:
    enabled: false
    namespace: ""
    jobLabel: ""
    interval: 30s
    scrapeTimeout: ""
    relabelings: []
    metricRelabelings: []
    selector: {}
    honorLabels: false
    labels: {}
    annotations: {}
  prometheusRule:
    enabled: false
    namespace: ""
    additionalLabels: {}
    rules: []
