
# Global parameters

global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  storageClass: ""
  security:
    allowInsecureImages: false
  compatibility:
    openshift:
      adaptSecurityContext: auto
# Common parameters

nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
kubeVersion: ""
extraDeploy: []
commonLabels: {}
commonAnnotations: {}
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
# Contour parameters

existingConfigMap: ""
configInline:
  disablePermitInsecure: false
  tls:
    fallback-certificate: {}
  accesslog-format: envoy
contour:
  enabled: true
  image:
    registry: ghcr.io
    repository: nix-containers/contour-nixchart
    tag: 1.32.1-debian-12-r0
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
  #
  contourConfigName: "contour"
  configPath: true
  #
  replicaCount: 1
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  topologySpreadConstraints: []
  containerPorts:
    xds: 8001
    metrics: 8000
  automountServiceAccountToken: true
  hostAliases: []
  updateStrategy: {}
  extraArgs: []
  resourcesPreset: "nano"
  resources: {}
  manageCRDs: true
  envoyServiceNamespace: ""
  envoyServiceName: ""
  leaderElectionResourceName: ""
  ingressStatusAddress: ""
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  podLabels: {}
  lifecycleHooks: {}
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  command: []
  args: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  podAnnotations: {}
  serviceAccount:
    create: true
    name: ""
    automountServiceAccountToken: false
    annotations: {}
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
    readOnlyRootFilesystem: true
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  certgen:
    serviceAccount:
      create: true
      name: ""
      automountServiceAccountToken: false
      annotations: {}
    certificateLifetime: 365
    automountServiceAccountToken: true
    networkPolicy:
      enabled: true
      allowExternal: true
      allowExternalEgress: true
      kubeAPIServerPorts: [443, 6443, 8443]
      extraIngress: []
      extraEgress: []
      ingressNSMatchLabels: {}
      ingressNSPodMatchLabels: {}
  tlsExistingSecret: ""
  service:
    type: ClusterIP
    ports:
      xds: 8001
      metrics: 8000
    nodePorts:
      xds: ""
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    loadBalancerClass: ""
    externalTrafficPolicy: Cluster
    annotations: {}
    extraPorts: []
    sessionAffinity: None
    sessionAffinityConfig: {}
  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true
    kubeAPIServerPorts: [443, 6443, 8443]
    extraIngress: []
    extraEgress: []
    ingressNSMatchLabels: {}
    ingressNSPodMatchLabels: {}
  initContainers: []
  sidecars: []
  extraVolumes: []
  extraVolumeMounts: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  ingressClass:
    name: ""
    create: true
    default: true
  debug: false
  logFormat: text
  kubernetesDebug: 0
  rootNamespaces: ""
  overloadManager:
    enabled: false
    maxHeapBytes: "2147483648"
  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""

# Envoy parameters
envoy:
  enabled: true
  image:
    registry: ghcr.io
    repository: nix-containers/envoy-nixchart
    tag: 1.34.5-debian-12-r0
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  priorityClassName: ""
  schedulerName: ""
  topologySpreadConstraints: []
  extraArgs: []
  automountServiceAccountToken: false
  hostAliases: []
  resourcesPreset: "nano"
  resources: {}
  command: []
  args: []
  shutdownManager:
    lifecycleHooks: {}
    extraArgs: []
    enabled: true
    resourcesPreset: "nano"
    containerPorts:
      http: 8090
    resources: {}
    containerSecurityContext:
      enabled: true
      seLinuxOptions: {}
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      privileged: false
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
      readOnlyRootFilesystem: true
    livenessProbe:
      enabled: true
      initialDelaySeconds: 120
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 3
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
    startupProbe:
      enabled: false
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    customLivenessProbe: {}
    customReadinessProbe: {}
    customStartupProbe: {}
  kind: daemonset
  replicaCount: 1
  lifecycleHooks: {}
  updateStrategy:
    type: RollingUpdate
  minReadySeconds: 0
  revisionHistoryLimit: 10
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 11
    targetCPU: ""
    targetMemory: ""
    behavior: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: ""
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    supplementalGroups: []
    fsGroup: 0
    sysctls: []
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
    readOnlyRootFilesystem: true
  hostNetwork: false
  dnsPolicy: ClusterFirst
  tlsExistingSecret: ""
  serviceAccount:
    create: true
    name: ""
    automountServiceAccountToken: false
    annotations: {}
  livenessProbe:
    enabled: true
    port: 8002
    initialDelaySeconds: 120
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    port: 8002
    initialDelaySeconds: 10
    periodSeconds: 3
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  startupProbe:
    enabled: false
    port: 8002
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  terminationGracePeriodSeconds: 300
  logLevel: info
  service:
    name: ""
    multiAz:
      enabled: false
      zones: []
    targetPorts:
      http: http
      https: https
      metrics: metrics
    type: LoadBalancer
    externalTrafficPolicy: Local
    labels: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    loadBalancerClass: ""
    ipFamilyPolicy: ""
    ipFamilies: []
    annotations: {}
    ports:
      http: 80
      https: 443
      metrics: 8002
    nodePorts:
      http: ""
      https: ""
      metrics: ""
    extraPorts: []
    sessionAffinity: None
    sessionAffinityConfig: {}
    exposeMetrics: false
  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true
    extraIngress: []
    extraEgress: []
    ingressNSMatchLabels: {}
    ingressNSPodMatchLabels: {}
  useHostPort:
    http: false
    https: false
    metrics: false
  useHostIP: false
  hostPorts:
    http: 80
    https: 443
    metrics: 8002
  hostIPs:
    http: 127.0.0.1
    https: 127.0.0.1
    metrics: 127.0.0.1
  containerPorts:
    http: 8080
    https: 8443
    metrics: 8002
  initContainers: []
  sidecars: []
  extraVolumes: []
  extraVolumeMounts: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""
  defaultInitContainers:
    initConfig:
      containerSecurityContext:
        enabled: true
        seLinuxOptions: {}
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        privileged: false
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: "RuntimeDefault"
      resourcesPreset: "nano"
      resources: {}

# Gateway API parameters

gatewayAPI:
  manageCRDs: false

# Default backend parameters

defaultBackend:
  enabled: false
  image:
    registry: ghcr.io
    repository: nix-containers/nginx-nixchart
    tag: 1.29.1-debian-12-r0
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  extraArgs: {}
  lifecycleHooks: {}
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumes: []
  extraVolumeMounts: []
  initContainers: []
  sidecars: []
  containerPorts:
    http: 8001
  updateStrategy: {}
  command: []
  args: []
  hostAliases: []
  replicaCount: 1
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
    readOnlyRootFilesystem: true
  resourcesPreset: "nano"
  resources: {}
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 0
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  startupProbe:
    enabled: false
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  podLabels: {}
  podAnnotations: {}
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: 60
  topologySpreadConstraints: []
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  service:
    type: ClusterIP
    ports:
      http: 80
    annotations: {}
  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true
    extraIngress: []
    extraEgress: []
    ingressNSMatchLabels: {}
    ingressNSPodMatchLabels: {}
  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""
ingress:
  enabled: false
  apiVersion: ""
  certManager: false
  annotations: {}
  hostname: contour.local
  path: /
  rulesOverride: []
  selfSigned: false
  ingressClassName: ""
  extraPaths: []
  tls: false
  pathType: ImplementationSpecific
  extraHosts: []
  extraTls: []
  secrets: []
  extraRules: []
# Metrics parameters
metrics:
  serviceMonitor:
    namespace: ""
    enabled: false
    jobLabel: "app.kubernetes.io/name"
    interval: ""
    metricRelabelings: []
    relabelings: []
    honorLabels: false
    scrapeTimeout: ""
    selector: {}
    labels: {}
  prometheusRule:
    enabled: false
    namespace: ""
    additionalLabels: {}
    rules: []
# Other parameters

rbac:
  create: true
  rules: []
tlsExistingSecret: ""
useCertManager: false
