
# Global parameters

global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  security:
    allowInsecureImages: false
  compatibility:
    openshift:
      adaptSecurityContext: auto

# Common parameters

kubeVersion: ""
apiVersions: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
commonLabels: {}
commonAnnotations: {}
clusterDomain: cluster.local
extraDeploy: []
usePasswordFiles: true
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity

# Default Init Container Parameters

defaultInitContainers:
  volumePermissions:
    enabled: false
    image:
      registry: ghcr.io
      repository: nix-containers/os-shell-nixchart
      tag: 12-debian-12-r51
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets: []
    containerSecurityContext:
      enabled: true
      seLinuxOptions: {}
      runAsUser: 0
      privileged: false
      allowPrivilegeEscalation: false
      capabilities:
        add: ["CHOWN"]
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
    resourcesPreset: "nano"
    resources: {}

# ClickHouse parameters

image:
  registry: ghcr.io
  repository: nix-containers/clickhouse-nixchart
  tag: v26.6.1
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
clusterName: default
auth:
  username: default
  password: ""
  existingSecret: ""
  existingSecretKey: ""
tls:
  enabled: false
  autoGenerated:
    enabled: true
    engine: helm
    certManager:
      existingIssuer: ""
      existingIssuerKind: ""
      keySize: 2048
      keyAlgorithm: RSA
      duration: 2160h
      renewBefore: 360h
  ca: ""
  existingCASecret: ""
  server:
    cert: ""
    key: ""
    existingSecret: ""
  keeper:
    cert: ""
    key: ""
    existingSecret: ""
logLevel: information
sampling:
  enabled: false
configuration: {}
existingConfigmap: ""
configdFiles: {}
existingConfigdConfigmap: ""
usersdFiles: {}
existingUsersdConfigmap: ""
existingUsersdSecret: ""
initdbScripts: {}
initdbScriptsSecret: ""
startdbScripts: {}
startdbScriptsSecret: ""
shards: 2
replicaCount: 3
distributeReplicasByZone: false
exposeMysql: true
exposePostgresql: true
containerPorts:
  http: 8123
  https: 8443
  tcp: 9000
  tcpSecure: 9440
  mysql: 9004
  postgresql: 9005
  interserver: 9009
  metrics: 8001
livenessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
startupProbe:
  enabled: false
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
customLivenessProbe: {}
customReadinessProbe: {}
customStartupProbe: {}
resourcesPreset: "small"
resources: {}
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001
containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
command: []
args: []
automountServiceAccountToken: false
hostAliases: []
podLabels: {}
podAnnotations: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
updateStrategy:
  type: RollingUpdate
  rollingUpdate: {}
podManagementPolicy: Parallel
priorityClassName: ""
topologySpreadConstraints: []
schedulerName: ""
terminationGracePeriodSeconds: ""
lifecycleHooks: {}
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
extraVolumes: []
extraVolumeMounts: []
extraVolumeClaimTemplates: []
sidecars: []
initContainers: []
pdb:
  create: true
  minAvailable: ""
  maxUnavailable: ""
autoscaling:
  vpa:
    enabled: false
    annotations: {}
    controlledResources: []
    maxAllowed: {}
    minAllowed: {}
    updatePolicy:
      updateMode: Auto

# ClickHouse Traffic Exposure parameters

service:
  type: ClusterIP
  perReplicaAccess: false
  ports:
    http: 8123
    https: 443
    tcp: 9000
    tcpSecure: 9440
    mysql: 9004
    postgresql: 9005
    interserver: 9009
    metrics: 8001
  nodePorts:
    http: ""
    https: ""
    tcp: ""
    tcpSecure: ""
    mysql: ""
    postgresql: ""
    interserver: ""
    metrics: ""
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerIPs: []
  loadBalancerAnnotations: []
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  annotations: {}
  extraPorts: []
  sessionAffinity: None
  sessionAffinityConfig: {}
  headless:
    annotations: {}
    extraPorts: []
ingress:
  enabled: false
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: clickhouse.local
  ingressClassName: ""
  path: /
  annotations: {}
  tls: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  extraRules: []
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
  addExternalClientAccess: true
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}

# ClickHouse Persistence parameters

persistentVolumeClaimRetentionPolicy:
  enabled: false
  whenScaled: Retain
  whenDeleted: Retain
persistence:
  enabled: true
  volumeName: data
  existingClaim: ""
  storageClass: ""
  labels: {}
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  selector: {}
  dataSource: {}
  mountPath: /nix-containers/clickhouse

# ClickHouse Keeper parameters

keeper:
  enabled: true
  image:
    registry: ghcr.io
    repository: nix-containers/clickhouse-keeper-nixchart
    tag: 25.7.5-debian-12-r0
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
  replicaCount: 3
  configuration: {}
  existingConfigmap: ""
  configdFiles: {}
  existingConfigdConfigmap: ""
  usersdFiles: {}
  existingUsersdConfigmap: ""
  existingUsersdSecret: ""
  containerPorts:
    tcp: 9181
    tcpSecure: 9281
    raft: 9234
  extraContainerPorts: []
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  startupProbe:
    enabled: false
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  resourcesPreset: "small"
  resources: {}
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  command: []
  args: []
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  automountServiceAccountToken: false
  hostAliases: []
  podLabels: {}
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: {}
  podManagementPolicy: Parallel
  priorityClassName: ""
  topologySpreadConstraints: []
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  lifecycleHooks: {}
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: []
  initContainers: []
  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""
  autoscaling:
    vpa:
      enabled: false
      annotations: {}
      controlledResources: []
      maxAllowed: {}
      minAllowed: {}
      updatePolicy:
        updateMode: Auto

  # ClickHouse Keeper Traffic Exposure parameters

  service:
    type: ClusterIP
    ports:
      tcp: 9181
      tcpSecure: 9281
      raft: 9234
    nodePorts:
      tcp: ""
      tcpSecure: ""
      raft: ""
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: Cluster
    annotations: {}
    extraPorts: []
    sessionAffinity: None
    sessionAffinityConfig: {}
    headless:
      annotations: {}
      extraPorts: []
  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true
    addExternalClientAccess: true
    extraIngress: []
    extraEgress: []
    ingressNSMatchLabels: {}
    ingressNSPodMatchLabels: {}

  # ClickHouse Keeper Persistence parameters

  persistentVolumeClaimRetentionPolicy:
    enabled: false
    whenScaled: Retain
    whenDeleted: Retain
  persistence:
    enabled: true
    existingClaim: ""
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}
    labels: {}
    selector: {}
    dataSource: {}
    mountPath: /nix-containers/clickhouse-keeper

# Other Parameters

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false

# Prometheus metrics parameters

metrics:
  enabled: false
  podAnnotations: {}
  serviceMonitor:
    enabled: false
    namespace: ""
    annotations: {}
    labels: {}
    jobLabel: ""
    honorLabels: false
    interval: ""
    scrapeTimeout: ""
    metricRelabelings: []
    relabelings: []
    selector: {}
  prometheusRule:
    enabled: false
    namespace: ""
    additionalLabels: {}
    rules: []

# External ClickHouse Keeper / Zookeeper parameters
externalZookeeper:
  servers: []
  port: 2888
